/// BN254 scalar field Fr arithmetic (Montgomery form, 256-bit limbs).
///
/// Field modulus P = 21888242871839275222246405745257275088548364400416034343698204186575808495617
///                 = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001
///
/// Implementation follows standard Montgomery multiplication algorithms.
/// See: Montgomery, P.L. (1985) "Modular multiplication without trial division"
/// Modular inverse uses the EVM `modexp` precompile (0x05) via Fermat's
/// little theorem: a^{-1} = a^(p-2) mod p.
///
/// This is custom no_std code — no audited BN254 Fr library exists for PolkaVM.
/// Correctness is verified by on-chain tests: the full UltraHonk verifier
/// (which depends on every Fr operation) produces identical results to
/// Barretenberg's `bb verify` for valid and invalid proofs.
use core::ops::{Add, Mul, Neg, Sub};
use pallet_revive_uapi::{CallFlags, HostFn, HostFnImpl as api};

/// P in 64-bit limbs (little-endian limb order)
pub const P: [u64; 4] = [
    0x43e1f593f0000001,
    0x2833e84879b97091,
    0xb85045b68181585d,
    0x30644e72e131a029,
];

/// -P^{-1} mod 2^64
const INV: u64 = 0xc2e1f593efffffff;

/// R = 2^256 mod P (Montgomery factor), little-endian limbs
pub const R: [u64; 4] = [
    0xac96341c4ffffffb,
    0x36fc76959f60cd29,
    0x666ea36f7879462e,
    0x0e0a77c19a07df2f,
];

/// R^2 mod P
pub const R2: [u64; 4] = [
    0x1bb8e645ae216da7,
    0x53fe3ab1e35c59e3,
    0x8c49833d53bb8085,
    0x0216d0b17f4e44a5,
];

/// Field element in Montgomery form: stores a·R mod P
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Fr(pub [u64; 4]);

impl Fr {
    pub const ZERO: Fr = Fr([0, 0, 0, 0]);
    pub const ONE: Fr = Fr(R); // 1·R mod P

    pub fn zero() -> Fr {
        Fr::ZERO
    }
    pub fn one() -> Fr {
        Fr::ONE
    }
    pub fn is_zero(self) -> bool {
        self.0 == [0, 0, 0, 0]
    }

    /// Construct from a small u64 (converts to Montgomery form)
    pub fn from_u64(v: u64) -> Fr {
        let raw = [v, 0, 0, 0];
        Fr(mont_mul(&raw, &R2))
    }

    /// Construct from big-endian 32-byte representation (reduces mod P, then to Montgomery)
    pub fn from_be_bytes(bytes: &[u8; 32]) -> Fr {
        let mut limbs = [0u64; 4];
        for i in 0..4 {
            let b = &bytes[(3 - i) * 8..(3 - i) * 8 + 8];
            limbs[i] = u64::from_be_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]]);
        }
        // Full reduction mod P: keccak outputs can be up to 2^256-1 ≈ 5.3*P,
        // so one subtraction is not sufficient. Loop until limbs < P.
        while geq_p(&limbs) {
            limbs = sub_mod(&limbs, &P, &P);
        }
        // Convert to Montgomery form: limbs * R mod P
        Fr(mont_mul(&limbs, &R2))
    }

    /// Return as big-endian 32 bytes (converts out of Montgomery)
    pub fn to_be_bytes(self) -> [u8; 32] {
        // Convert from Montgomery: self * 1 / R mod P
        let normal = mont_mul(&self.0, &[1, 0, 0, 0]);
        let mut out = [0u8; 32];
        for i in 0..4 {
            let b = normal[3 - i].to_be_bytes();
            out[i * 8..i * 8 + 8].copy_from_slice(&b);
        }
        out
    }

    pub fn inverse(self) -> Option<Fr> {
        if self.is_zero() {
            return None;
        }
        // Convert from Montgomery form, invert via modexp precompile (a^(p-2) mod p),
        // then convert back to Montgomery form.
        let normal = mont_mul(&self.0, &[1, 0, 0, 0]);
        let inv = mod_inverse_normal_modexp(&normal)?;
        // Convert back to Montgomery: inv * R = mont_mul(inv, R^2 / R) = mont_mul(inv, R2)
        Some(Fr(mont_mul(&inv, &R2)))
    }
}

// ─── Hoisted Montgomery-form constants ──────────────────────────────────────
//
// All values below are precomputed Mont(x) = x · R mod P limbs.  Generated by
// /tmp/compute_fr_consts.js (sanity-checked against Fr::ONE = R).  Used to
// avoid recomputing `Fr::from_u64(N)` / `fr_from_hex(...)` on the hot path.

pub const FR_TWO: Fr = Fr([
    0x592c68389ffffff6,
    0x6df8ed2b3ec19a53,
    0xccdd46def0f28c5c,
    0x1c14ef83340fbe5e,
]);
pub const FR_THREE: Fr = Fr([
    0x05c29c54effffff1,
    0xa4f563c0de22677d,
    0x334bea4e696bd28a,
    0x2a1f6744ce179d8e,
]);
pub const FR_FOUR: Fr = Fr([
    0x6e76dadd4fffffeb,
    0xb3bdf20e03c9c415,
    0xe16a48076063c05b,
    0x07c5909386eddc93,
]);
pub const FR_FIVE: Fr = Fr([
    0x1b0d0ef99fffffe6,
    0xeaba68a3a32a913f,
    0x47d8eb76d8dd0689,
    0x15d0085520f5bbc3,
]);
pub const FR_SIX: Fr = Fr([
    0xc7a34315efffffe1,
    0x21b6df39428b5e68,
    0xae478ee651564cb8,
    0x23da8016bafd9af2,
]);
pub const FR_SEVEN: Fr = Fr([
    0x3057819e4fffffdb,
    0x307f6d866832bb01,
    0x5c65ec9f484e3a89,
    0x0180a96573d3d9f8,
]);
pub const FR_NINE: Fr = Fr([
    0x8983e9d6efffffd1,
    0x9e785ab1a6f45554,
    0x2943337e3940c6e5,
    0x1d9598e8a7e39857,
]);
pub const FR_SEVENTEEN: Fr = Fr([
    0x66719f918fffffa7,
    0x05f43ecdae87dd7f,
    0xec17c38cfa08479d,
    0x2d20ba0fb5bf517e,
]);

pub const FR_NEG_ONE: Fr = Fr([
    0x974bc177a0000006,
    0xf13771b2da58a367,
    0x51e1a2470908122e,
    0x2259d6b14729c0fa,
]);
pub const FR_NEG_TWO: Fr = Fr([
    0xeab58d5b5000000b,
    0xba3afb1d3af7d63d,
    0xeb72fed7908ecc00,
    0x144f5eefad21e1ca,
]);
pub const FR_NEG_THREE: Fr = Fr([
    0x3e1f593f00000010,
    0x833e84879b970914,
    0x85045b68181585d2,
    0x0644e72e131a029b,
]);
pub const FR_NEG_HALF: Fr = Fr([
    0xcba5e0bbd0000003,
    0x789bb8d96d2c51b3,
    0x28f0d12384840917,
    0x112ceb58a394e07d,
]);

pub const FR_LIMB_2_68: Fr = Fr([
    0x61b9523c75fb5855,
    0x4e8dd9eec3c165ad,
    0x145edf68beef42f6,
    0x0160cbd9f670a49f,
]);
pub const FR_SUBLIMB_2_14: Fr = Fr([
    0x36c694550ffead6f,
    0xb1e9be3c37577218,
    0x9e7d8ca3df11f427,
    0x279be39aed6d3304,
]);

pub const BARYCENTRIC_DENOMS: [Fr; 8] = [
    Fr([
        0x2330830990006827,
        0x3645d47de0fb29b5,
        0xb08cc36a469a4e86,
        0x1f269efc77a0593b,
    ]),
    Fr([
        0x3edb076dfffff120,
        0xfbe0c9ed59958f2e,
        0x55f305399bfd9649,
        0x2bf1132a3dd1936a,
    ]),
    Fr([
        0xc2f84be8a00004f6,
        0x7182578bddf470a6,
        0x5e39d76677ac5e25,
        0x119d2de92c308ef8,
    ]),
    Fr([
        0x354cfb3b8ffffd07,
        0x7db2808e27c0602d,
        0x1960c47906805313,
        0x25d2cc80937ae3fb,
    ]),
    Fr([
        0x0e94fa58600002fa,
        0xaa8167ba51f91064,
        0x9eef813d7b010549,
        0x0a9181f24db6bc2e,
    ]),
    Fr([
        0x80e9a9ab4ffffb0b,
        0xb6b190bc9bc4ffea,
        0x5a166e5009d4fa37,
        0x1ec72089b5011131,
    ]),
    Fr([
        0x0506ee25f0000ee1,
        0x2c531e5b2023e163,
        0x625d407ce583c213,
        0x04733b48a3600cbf,
    ]),
    Fr([
        0x20b1728a5fff97da,
        0xf1ee13ca98be46dc,
        0x07c3824c3ae709d6,
        0x113daf76699146ee,
    ]),
];

pub const POSEIDON_DIAG: [Fr; 4] = [
    Fr([
        0x78b3c4df7b603c75,
        0xdd54552f4a97b9e3,
        0xc9ceb940f70388e9,
        0x300af8e86f112b7e,
    ]),
    Fr([
        0x00deb14139b1ef67,
        0xccb2bdefcca2343d,
        0x6c43a052dbe2f558,
        0x1063a869506e775c,
    ]),
    Fr([
        0x94eea894378e2f93,
        0x93faf7c07882666b,
        0x21288cc59995cfdc,
        0x027e7283b9b0b7d3,
    ]),
    Fr([
        0xb35e450fba986fc1,
        0x926ccb787560ef38,
        0x1e1e2685895114e8,
        0x2841f4314cbcead3,
    ]),
];

impl Add for Fr {
    type Output = Fr;
    fn add(self, rhs: Fr) -> Fr {
        Fr(add_mod(&self.0, &rhs.0, &P))
    }
}

impl Sub for Fr {
    type Output = Fr;
    fn sub(self, rhs: Fr) -> Fr {
        Fr(sub_mod(&self.0, &rhs.0, &P))
    }
}

impl Neg for Fr {
    type Output = Fr;
    fn neg(self) -> Fr {
        if self.is_zero() {
            self
        } else {
            Fr(sub_mod(&P, &self.0, &P))
        }
    }
}

impl Mul for Fr {
    type Output = Fr;
    fn mul(self, rhs: Fr) -> Fr {
        Fr(mont_mul(&self.0, &rhs.0))
    }
}

/// Multiply-accumulate: acc + a*b + carry_in → (lo, hi).
fn mac(acc: u64, a: u64, b: u64, carry: u64) -> (u64, u64) {
    let r = acc as u128 + (a as u128) * (b as u128) + carry as u128;
    (r as u64, (r >> 64) as u64)
}

/// Montgomery multiplication: computes (a * b) / R mod P using CIOS.
fn mont_mul(a: &[u64; 4], b: &[u64; 4]) -> [u64; 4] {
    let mut t0: u64 = 0;
    let mut t1: u64 = 0;
    let mut t2: u64 = 0;
    let mut t3: u64 = 0;
    let mut t4: u64 = 0;

    // i = 0
    {
        let ai = a[0];
        let (r, c) = mac(t0, ai, b[0], 0);
        t0 = r;
        let (r, c) = mac(t1, ai, b[1], c);
        t1 = r;
        let (r, c) = mac(t2, ai, b[2], c);
        t2 = r;
        let (r, c) = mac(t3, ai, b[3], c);
        t3 = r;
        t4 = t4.wrapping_add(c);
        let m = t0.wrapping_mul(INV);
        let (_, c) = mac(t0, m, P[0], 0);
        let (r, c) = mac(t1, m, P[1], c);
        t0 = r;
        let (r, c) = mac(t2, m, P[2], c);
        t1 = r;
        let (r, c) = mac(t3, m, P[3], c);
        t2 = r;
        t3 = t4.wrapping_add(c);
        t4 = 0;
    }
    // i = 1
    {
        let ai = a[1];
        let (r, c) = mac(t0, ai, b[0], 0);
        t0 = r;
        let (r, c) = mac(t1, ai, b[1], c);
        t1 = r;
        let (r, c) = mac(t2, ai, b[2], c);
        t2 = r;
        let (r, c) = mac(t3, ai, b[3], c);
        t3 = r;
        t4 = t4.wrapping_add(c);
        let m = t0.wrapping_mul(INV);
        let (_, c) = mac(t0, m, P[0], 0);
        let (r, c) = mac(t1, m, P[1], c);
        t0 = r;
        let (r, c) = mac(t2, m, P[2], c);
        t1 = r;
        let (r, c) = mac(t3, m, P[3], c);
        t2 = r;
        t3 = t4.wrapping_add(c);
        t4 = 0;
    }
    // i = 2
    {
        let ai = a[2];
        let (r, c) = mac(t0, ai, b[0], 0);
        t0 = r;
        let (r, c) = mac(t1, ai, b[1], c);
        t1 = r;
        let (r, c) = mac(t2, ai, b[2], c);
        t2 = r;
        let (r, c) = mac(t3, ai, b[3], c);
        t3 = r;
        t4 = t4.wrapping_add(c);
        let m = t0.wrapping_mul(INV);
        let (_, c) = mac(t0, m, P[0], 0);
        let (r, c) = mac(t1, m, P[1], c);
        t0 = r;
        let (r, c) = mac(t2, m, P[2], c);
        t1 = r;
        let (r, c) = mac(t3, m, P[3], c);
        t2 = r;
        t3 = t4.wrapping_add(c);
        t4 = 0;
    }
    // i = 3
    {
        let ai = a[3];
        let (r, c) = mac(t0, ai, b[0], 0);
        t0 = r;
        let (r, c) = mac(t1, ai, b[1], c);
        t1 = r;
        let (r, c) = mac(t2, ai, b[2], c);
        t2 = r;
        let (r, c) = mac(t3, ai, b[3], c);
        t3 = r;
        t4 = t4.wrapping_add(c);
        let m = t0.wrapping_mul(INV);
        let (_, c) = mac(t0, m, P[0], 0);
        let (r, c) = mac(t1, m, P[1], c);
        t0 = r;
        let (r, c) = mac(t2, m, P[2], c);
        t1 = r;
        let (r, c) = mac(t3, m, P[3], c);
        t2 = r;
        t3 = t4.wrapping_add(c);
    }

    reduce_once(&[t0, t1, t2, t3], &P)
}

/// 4-limb subtraction: a - b, returns (result, borrow).
/// Uses only u64 operations (overflowing_sub) — no i128.
/// Matches PoseidonPolkaVM's sub4 approach.
fn sub4(a: &[u64; 4], b: &[u64; 4]) -> ([u64; 4], bool) {
    let mut r = [0u64; 4];
    let mut borrow: u64 = 0;

    let (d, b1) = a[0].overflowing_sub(b[0]);
    let (d2, b2) = d.overflowing_sub(borrow);
    r[0] = d2;
    borrow = (b1 as u64) + (b2 as u64);

    let (d, b1) = a[1].overflowing_sub(b[1]);
    let (d2, b2) = d.overflowing_sub(borrow);
    r[1] = d2;
    borrow = (b1 as u64) + (b2 as u64);

    let (d, b1) = a[2].overflowing_sub(b[2]);
    let (d2, b2) = d.overflowing_sub(borrow);
    r[2] = d2;
    borrow = (b1 as u64) + (b2 as u64);

    let (d, b1) = a[3].overflowing_sub(b[3]);
    let (d2, b2) = d.overflowing_sub(borrow);
    r[3] = d2;
    borrow = (b1 as u64) + (b2 as u64);

    (r, borrow != 0)
}

/// 4-limb addition: a + b, returns (result, carry).
/// Uses only u64 operations — no u128.
fn add4(a: &[u64; 4], b: &[u64; 4]) -> ([u64; 4], bool) {
    let mut r = [0u64; 4];
    let mut carry: u64 = 0;

    let (s, c1) = a[0].overflowing_add(b[0]);
    let (s2, c2) = s.overflowing_add(carry);
    r[0] = s2;
    carry = (c1 as u64) + (c2 as u64);

    let (s, c1) = a[1].overflowing_add(b[1]);
    let (s2, c2) = s.overflowing_add(carry);
    r[1] = s2;
    carry = (c1 as u64) + (c2 as u64);

    let (s, c1) = a[2].overflowing_add(b[2]);
    let (s2, c2) = s.overflowing_add(carry);
    r[2] = s2;
    carry = (c1 as u64) + (c2 as u64);

    let (s, c1) = a[3].overflowing_add(b[3]);
    let (s2, c2) = s.overflowing_add(carry);
    r[3] = s2;
    carry = (c1 as u64) + (c2 as u64);

    (r, carry != 0)
}

/// Addition mod m
fn add_mod(a: &[u64; 4], b: &[u64; 4], m: &[u64; 4]) -> [u64; 4] {
    let (r, carry) = add4(a, b);
    // If carry, or r >= m, subtract m
    let (sub_r, borrow) = sub4(&r, m);
    if carry || !borrow {
        sub_r
    } else {
        r
    }
}

/// Subtraction mod m: a - b mod m
fn sub_mod(a: &[u64; 4], b: &[u64; 4], m: &[u64; 4]) -> [u64; 4] {
    let (r, borrowed) = sub4(a, b);
    if borrowed {
        // Add m back
        let (r2, _) = add4(&r, m);
        r2
    } else {
        r
    }
}

/// Compare a >= P (the BN254 Fr modulus), used for full reduction.
fn geq_p(a: &[u64; 4]) -> bool {
    // Try subtracting P; if no borrow, a >= P
    let (_, borrow) = sub4(a, &P);
    !borrow
}

/// Reduce once: if a >= m, return a - m, else a.
/// Only correct when a < 2m (single reduction suffices for montgomery output).
fn reduce_once(a: &[u64; 4], m: &[u64; 4]) -> [u64; 4] {
    let (sub_r, borrow) = sub4(a, m);
    if !borrow {
        sub_r // a >= m, return a - m
    } else {
        *a // a < m, keep as is
    }
}

fn is_zero256(a: &[u64; 4]) -> bool {
    a[0] == 0 && a[1] == 0 && a[2] == 0 && a[3] == 0
}

// ─── modexp-precompile-backed inverse ───────────────────────────────────────
//
// Big-endian 32-byte encoding of P (BN254 Fr modulus).
const P_BE: [u8; 32] = [
    0x30, 0x64, 0x4e, 0x72, 0xe1, 0x31, 0xa0, 0x29, 0xb8, 0x50, 0x45, 0xb6, 0x81, 0x81, 0x58, 0x5d,
    0x28, 0x33, 0xe8, 0x48, 0x79, 0xb9, 0x70, 0x91, 0x43, 0xe1, 0xf5, 0x93, 0xf0, 0x00, 0x00, 0x01,
];

// Big-endian 32-byte encoding of P - 2 (the Fermat exponent).
const P_MINUS_2_BE: [u8; 32] = [
    0x30, 0x64, 0x4e, 0x72, 0xe1, 0x31, 0xa0, 0x29, 0xb8, 0x50, 0x45, 0xb6, 0x81, 0x81, 0x58, 0x5d,
    0x28, 0x33, 0xe8, 0x48, 0x79, 0xb9, 0x70, 0x91, 0x43, 0xe1, 0xf5, 0x93, 0xef, 0xff, 0xff, 0xff,
];

fn modexp_precompile_address() -> [u8; 20] {
    let mut a = [0u8; 20];
    a[19] = 0x05;
    a
}

/// Convert 4 little-endian u64 limbs to a big-endian 32-byte buffer.
fn limbs_to_be_bytes(a: &[u64; 4]) -> [u8; 32] {
    let mut out = [0u8; 32];
    for i in 0..4 {
        let b = a[3 - i].to_be_bytes();
        out[i * 8..i * 8 + 8].copy_from_slice(&b);
    }
    out
}

/// Convert a 32-byte big-endian buffer to 4 little-endian u64 limbs.
fn be_bytes_to_limbs(bytes: &[u8; 32]) -> [u64; 4] {
    let mut limbs = [0u64; 4];
    for i in 0..4 {
        let b = &bytes[(3 - i) * 8..(3 - i) * 8 + 8];
        limbs[i] = u64::from_be_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]]);
    }
    limbs
}

/// Modular inverse in NORMAL (non-Montgomery) form via the EVM `modexp`
/// precompile at address 0x05, computing `a^(p-2) mod p` (Fermat's little
/// theorem).  Returns None if `a == 0`.  Assumes P is an odd prime.
///
/// modexp input layout (EIP-198):
///   [0..32):   len(B) = 32  (big-endian u256)
///   [32..64):  len(E) = 32
///   [64..96):  len(M) = 32
///   [96..128): B  (big-endian)
///   [128..160): E = p - 2  (big-endian)
///   [160..192): M = p      (big-endian)
/// Output: 32 bytes big-endian `B^E mod M`.
fn mod_inverse_normal_modexp(a: &[u64; 4]) -> Option<[u64; 4]> {
    if is_zero256(a) {
        return None;
    }

    let base_be = limbs_to_be_bytes(a);

    let mut input = [0u8; 192];
    // len(B), len(E), len(M) — all 32, encoded as big-endian u256.
    input[31] = 32;
    input[63] = 32;
    input[95] = 32;
    // B
    input[96..128].copy_from_slice(&base_be);
    // E = p - 2
    input[128..160].copy_from_slice(&P_MINUS_2_BE);
    // M = p
    input[160..192].copy_from_slice(&P_BE);

    let mut output = [0u8; 32];
    let mut output_ref: &mut [u8] = &mut output;
    let target = modexp_precompile_address();
    let gas = api::gas_left() / 2;
    let _ = api::call(
        CallFlags::empty(),
        &target,
        gas,
        u64::MAX,
        &[0u8; 32], // deposit
        &[0u8; 32], // value
        &input,
        Some(&mut output_ref),
    );

    Some(be_bytes_to_limbs(&output))
}
