[package]
name = "honk-verifier"
version = "0.1.0"
edition = "2021"
autobins = false

[lib]
name = "honk_verifier"
path = "src/main.rs"
crate-type = ["cdylib"]

[[test]]
name = "verify_test"
path = "tests/verify_test.rs"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
overflow-checks = false

[dependencies]
polkavm-derive = "0.30"
picoalloc = { version = "5", default-features = false }
tiny-keccak = { version = "2.0", features = ["keccak"] }
pallet-revive-uapi = { version = "0.10", default-features = false }
