[package]
name = "honk-verifier"
version = "0.1.0"
edition = "2021"
autobins = false

[lib]
name = "honk_verifier"
path = "src/main.rs"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
overflow-checks = false

[dependencies]
polkavm-derive = "0.30"
simplealloc = { version = "0.0.1", git = "https://github.com/paritytech/polkavm.git" }
pallet-revive-uapi = { version = "0.10", default-features = false }
